name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Docker Build
      uses: docker/setup-buildx-action@v3.10.0
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: Programa
    - name: Docker login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Docker push
      uses: docker/build-push-action@v6.15.0
      with:
        file: ./Dockerfile
        context: .
        push: true
        tags: leoalmeida/go_ci:${{github.run_number}}
