name: Go

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Docker Build
      uses: docker/setup-buildx-action@v3.10.0

    - name: Docker login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_KEY }}
      