name: Entrega continua

on:
  workflow_call:

jobs:
  EC2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: Programa
    
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "postgres-data"
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export DB_HOST=${{ secrets.DB_HOST }}
          export DB_USER=${{ secrets.DB_USER }}
          export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          export DB_NAME=${{ secrets.DB_NAME }}
          export DB_PORT=${{ secrets.DB_PORT }}
          export PORT=8000
          chmod +x main
          nohup ./main > nohup.out 2> nohup.err < /dev/null &
        
