name: Entrega continua

on:
  workflow_call:

jobs:
  ec2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.2.1
      with:
        name: Programa
        path: main
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "/node_modules/, postgres-data"
        
