name: ECS

on:
  workflow_call:

jobs:
  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: Configurar Credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        
    - name: Descrever task definition
      run: aws ecs describe-task-definition --task-definition Tarefa_API-go --query taskDefinition > task-definition.json

    - name: Fill new image in ECS task def
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: Go
        image: leoalmeida/go_ci:${{github.run_number}}
        environment-variables: |
          DB_HOST=${{secrets.DB_HOST}}
          DB_USER=${{secrets.DB_USER}}
          DB_PASSWORD=${{secrets.DB_PASSWORD}}
          DB_NAME=${{secrets.DB_NAME}}
          DB_PORT=${{secrets.DB_PORT}}
          PORT=8000

    - name: Deploy Amazon ECS task def
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: Tarefa_API-go-service-onmfgr5i
        cluster: APP_go
        wait-for-service-stability: true
