name: ECS

on:
  workflow_call:

jobs:
  ECS:
    runs-on: ubuntu-latest
    steps:
    - name: Configurar Credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        
    - name: Descrever task definition
      run: aws ecs describe-task-definition --task-definition Tarefa_API-go --query taskDefinition > task-definition.json
    
    - name: Login to amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Build, tag e push da imagem para o Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: my-ecr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
      
    - name: Fill new image in ECS task def
      id: task-def
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: task-definition.json
        container-name: my-container
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task def
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: my-service
        cluster: my-cluster
        wait-for-service-stability: true
