name: Kubernetes

on:
  workflow_call:

jobs:
  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Configurar Credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog init

    - run: terraform -chdir=Infra_CI/env/Homolog destroy -auto-approve
    #- run: return 1

    - run: terraform -chdir=Infra_CI_Kubernetes/env/Homolog apply -auto-approve
    
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v4
      
    - run: aws sts get-caller-identity
    
    - run: aws eks update-kubeconfig --region us-east-2 --name homolog2
    
    - run: kubectl get svc