name: Load Test

on:
  workflow_call:

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Credenciais AWS
      uses: aws-actions/configure-aws-credentials@v4.1.0
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}  

    - run: git clone https://github.com/leollo98/Infra_CI.git
